### ISSUE TITLE
feature request: example for text classification

### ISSUE THREAD

**Issue by koaning** [ines/spacy-course#30]
First of all: *thank you*. I've learned an amazing amount in a super short time from your work here. 

I do have a small request that might help others. After the course I wanted to try to train a text classification example and I could not figure what I was doing wrong (i created a stackoverflow question [here](https://stackoverflow.com/questions/56281633/train-spacy-for-text-classification)) even though training for entity detection worked just fine. 

A code example/assignment on text classification on an entire document might be nice to add to the course as an example (there's a lot of use-cases for it) and it might help others too. 

Should I get the code to work, I wouldn't mind giving a try for a PR either, should that be welcome.

**Comment by ines** [comment]
Thanks! I just left a separate comment on your Stack Overlow issue – looks like you did all the "hard parts" correctly and it came down to a small mistake in the way the dictionary of annotations was formatted 🙂

When I originally developed the contents for this course, text classification was still a super new feature in spaCy and not as mature as it is now. So that's why it's not really covered much in the course. I wouldn't necessarily want to change the existing course to add more content – only to update it in case small things change in spaCy's API, and of course to fix typos etc. But it's true that we currently don't really have many simple text classification examples, not even in the [spaCy docs](https://spacy.io/usage/training). So improving that would be great.

**Comment by koaning** [comment]
d0h! I knew it had to be something like that. 

If you appreciate a similar script somewhere in the docs somewhere I'll gladly contribute. If not, thanks again :)
