### ISSUE TITLE
Chapter 1, section 10-11: "ORTH" vs "TEXT" in pattern matching

### ISSUE THREAD

**Issue by thorbjornwolf** [ines/spacy-course#4]
Hi Ines! 
This is :heart_eyes: 
Great UI _and_ content. Really great work!

So far (Chapter 1, section 11), I've only been confused twice: Once when I had to install the `en_core_web_sm` _myself_ (I don't mind, though, it was easy to find out how), and now in section 11.
In section 10, we learned to use the pattern key `ORTH` to do exact text matching, but section 11 expects the [newer v2.1 `TEXT`](https://spacy.io/usage/rule-based-matching#adding-patterns-attributes) key (nice docs by the way).

I think the two sections should be aligned, or we/you should tell students that they can use either. Having not used spacy before, I strongly prefer the new `TEXT` key (what is `ORTH` even?) :grin: 

My initial investigation used the very neat `spacy.explain` feature, which does not yet know either word - I'm not sure if it is meant to also explain the pattern matching keys.

At any rate, thank you for your very nice and accessible work!

**Comment by ines** [comment]
Thanks! 🙏 

And sorry, that's definitely a mistake – I must have used an older version of the slides that didn't yet include this change. Already fixed this! 

The change to `TEXT` in spaCy v2.1 was actually directly inspired by this course when I realised that `ORTH` was just really difficult to explain, because it kinda made no sense. The obvious question would always be, why is it not `TEXT`? The `ORTH` is a reference to "orthography" and the `Token.orth` (hash ID of the token) and `Token.orth_` (string value of the token and the same as `Token.text` – only really exists for consistency and isn't normall used).

> I'm not sure if it is meant to also explain the pattern matching keys.

`spacy.explain` currently only explains labels of the label schemes and not attributes etc.

> Once when I had to install the `en_core_web_sm` *myself*

Which exercise are you referring to here? And you mean *load* the model with `spacy.load`, right?

**Comment by thorbjornwolf** [comment]
Thanks for the swift response!

> `spacy.explain` currently only explains labels of the label schemes and not attributes etc.

All right, thanks!

> Which exercise are you referring to here? And you mean _load_ the model with `spacy.load`, right?

When I tried to _load_ the model with `spacy.load`, I had to _install_ it first. Sorry for the unclarity :smile: I have derived issue #5 to delve into this part.

I can validate that the ORTH->TEXT transformation is complete - at least in my browser - so I think we can close this issue :ok_hand:
