### ISSUE TITLE
Ch 2, section 7: `result` not in code

### ISSUE THREAD

**Issue by thorbjornwolf** [ines/spacy-course#6]
It's me again! Let me know if this gets annoying, or if you prefer feedback in a different channel.

The first multiple-choice option in chapter 2, section 7, part 1 refers to a `result` object, which is not in the code. Looks like a leftover from a refactor :-)

The text is this: "The tokens in the `result` should be converted back to `Token` objects. This will let you reuse them in spaCy."

**Comment by ines** [comment]
Thanks so much for all your feedback, this is super useful! I think GitHub issues are perfect for this, and I definitely prefer having one issue per topic/bug/question.

> The text is this: "The tokens in the result should be converted back to Token objects. This will let you reuse them in spaCy."

Ahh, I think the version of the course materials I used here wasn't the 100% latest version and this was a problem I introduced when simplifying the exercise. Originally, it was a bit more complex. but users on DataCamp found it too difficult and confusing, since the format is very different from the usual style of exercises on the platform.

I think I'm actually going to change the code back to be slightly more complex. It's not like you're going to lose XP or other points here if you ask for a hint or request the solution. And if someone doesn't like it, they can just skip it and move on 🙂
