### ISSUE TITLE
test_02_09 looks for the small, not the medium, model

### ISSUE THREAD

**Issue by thorbjornwolf** [ines/spacy-course#7]
The exercise in chapter 2, section 9 where we want to inspect the "bananas" word vector has an imperfect test. It checks for the presence of "spacy.load('en_core_web_sm')", and not the model we've learned to use, namely `en_core_web_md`.

[The file is here](https://github.com/ines/spacy-course/blob/master/exercises/test_02_09.py).

Very easy to read test module, though, I like it!

Just a side-thought: Could it be interesting to use [Black](https://github.com/ambv/black) to normalize the solution code formatting before checking it? I see this test checks against the two main string quotes `"` and `'`: if that is a recurring thing, Black might help by forcing alllll the code to adhere to a certain, deterministic formatting choice. On the other hand, applying it just might increase complexity, and may reduce the readability of the tests :man_shrugging:

**Comment by ines** [comment]
Thanks! And yes, that's a bug (probably copy-paste mistake) – fixing 👍

> Just a side-thought: Could it be interesting to use Black to normalize the solution code formatting before checking it? 

Yessss, so cool you mentioned this – I actually had the exact same idea yesterday! 👍 This would definitely make it so much easier to validate the string code, because we can make more assumptions about it – and the user could still write their code however they want to. I'll need to play around with this a bit, though, to make sure there are no unintended side-effects (and how to best do it from within Python – I've only ever used Black via a plugin or on the command line before).
