### ISSUE TITLE
isinstance(similarity, float) not working for np.float32

### ISSUE THREAD

**Issue by thorbjornwolf** [ines/spacy-course#9]
### Problem
Chapter 2, section 10, part 2. [Test file here](https://github.com/ines/spacy-course/blob/master/exercises/test_02_10_02.py). The check `isinstance(similarity, float)` fails.

Edit: Also [part 3](https://github.com/ines/spacy-course/blob/master/exercises/test_02_10_03.py#L8)

I dug a bit around, and found that `Token.similarity()` returns a numpy.float32, not a python float.

```python
In [2]: type(similarity)                                                                                    
Out[2]: numpy.float32

In [3]: isinstance(similarity, float)                                                                       
Out[3]: False
```

### Solution proposals
Now, I'm unsure how to best proceed: It _does_ return a floating point value, just not the exact kind that the test expects. Here are two suggestions:

#### 1: Use `np.floating` in addition to `float`

```python
In [17]: isinstance(similarity, np.floating)                
Out[17]: True

In [18]: isinstance(1.0, np.floating)  # Why we need to ALSO check isinstance(x, float)
Out[18]: False
```

It is surprisingly hard to find docs to link for `numpy.floating` :thinking:
Instead, here is its docstring: "Abstract base class of all floating-point scalar types."

#### 2: Try casting to float
Check the value's range while we're there

```python
In [22]: 0 <= float(similarity) <= 1                        
Out[22]: True
```

Edit edit: For what it is worth, using this in the solution passes the test: 

```python
...
similarity = span1.similarity(span2)
similarity = float(similarity)
print(similarity)
```

### Additional considerations
- Maybe the [docs](https://spacy.io/api/token#similarity) should reflect that minuscule difference? I'm not sure if it is important in practice.
- Along with #7, this is a case where the pre-made solution fails on its associated test. We could perhaps make a script for checking each solution against its test? I'll spin off a separate issue for this.

**Comment by ines** [comment]
Ahh, thanks – and yes, you're right. It'd be nice if we could avoid using numpy in the tests explicitly, since I'm worried that this might introduce other unintended side-effects and random type complexity.

I've just changed it to ` 0 <= float(similarity) <= 1` for now so that the tests at least pass. It'd still result in false positives for boolean values and it'd raise an error for strings... but we also don't necessarily need to cover all edge cases. There's a lot of weird stuff that could happen if a user just typed in something completely arbitrary – but I definitely want to make sure the tests cover the most common mistakes.

Also, alternative hacky idea: regex on `str(similarity)` 😅

**Comment by thorbjornwolf** [comment]
:100: agreed!

Haha yes I also thought about str/repr: Is there a dot surrounded by numbers? Pass! :grin: (It feels dirty somehow, though, although I can't off the top of my head explain why)

I see your commits, and think this one can be closed :tada:
